[package]
name = "relm_first"
version = "0.1.0"
authors = ["davidroeca <david.roeca@gmail.com>"]

[dependencies]
gtk = { version = "^0.4.0", features = ["v3_16"] }
relm = "^0.14.0"
relm-derive = "^0.14.0"
